// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
pub type ComponentName = String;

#[rustfmt::skip]
pub type MigrationIdentifier = String;

#[rustfmt::skip]
pub type RecordKind = String;

#[rustfmt::skip]
pub type RawByte = Integer;

#[rustfmt::skip]
pub type RawBytes = Vec<RawByte>;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContractVersion(pub RawBytes);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Version {
    pub major: Integer,
    pub minor: Integer,
    pub patch: Integer,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SupportedMigration {
    pub component: ComponentName,
    pub source: Version,
    pub target: Version,
    pub identifier: MigrationIdentifier,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Inspection {
    All,
    Component(ComponentName),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Attempt {
    pub component: ComponentName,
    pub source: Version,
    pub target: Version,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReportQuery {
    All,
    Component(ComponentName),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InspectionReported(pub Vec<SupportedMigration>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Completion {
    pub component: ComponentName,
    pub source: Version,
    pub target: Version,
    pub migration: MigrationIdentifier,
    pub changed_records: Integer,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RejectionReason {
    UnsupportedMigration,
    ComponentMismatch,
    MigrationFailed,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Rejection {
    pub component: ComponentName,
    pub source: Version,
    pub target: Version,
    pub reason: RejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Reported {
    pub completions: Vec<Completion>,
    pub rejections: Vec<Rejection>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum UnimplementedReason {
    NotBuiltYet,
    IntegrationNotLanded,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplemented(pub UnimplementedReason);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Date {
    pub year: Integer,
    pub month: Integer,
    pub day: Integer,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Time {
    pub hour: Integer,
    pub minute: Integer,
    pub second: Integer,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HandoverMarker {
    pub component: ComponentName,
    pub schema_hash: ContractVersion,
    pub state_sequence: Integer,
    pub mirrored_write_count: Integer,
    pub record_frontier: Option<Integer>,
    pub recorded_at_date: Date,
    pub recorded_at_time: Time,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MarkerRequest(pub ComponentName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReadinessReport {
    pub component: ComponentName,
    pub source_marker: HandoverMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CompletionReport {
    pub component: ComponentName,
    pub accepted_marker: HandoverMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MirrorPayload {
    pub component: ComponentName,
    pub source_version: ContractVersion,
    pub target_version: ContractVersion,
    pub kind: RecordKind,
    pub payload: RawBytes,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DivergencePayload {
    pub component: ComponentName,
    pub source_version: ContractVersion,
    pub target_version: ContractVersion,
    pub reason: DivergenceReason,
    pub kind: RecordKind,
    pub payload: RawBytes,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecoveryRequest {
    pub component: ComponentName,
    pub failure_identifier: Integer,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HandoverAcceptance(pub HandoverMarker);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HandoverFinalization(pub HandoverMarker);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MirrorAcknowledgement {
    pub component: ComponentName,
    pub mirrored_write_count: Integer,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DivergenceAcknowledgement {
    pub component: ComponentName,
    pub divergence_identifier: Integer,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecoveryResult {
    pub component: ComponentName,
    pub recovered: Boolean,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HandoverRejection {
    pub component: ComponentName,
    pub reason: HandoverRejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum HandoverRejectionReason {
    SchemaMismatch,
    StateSequenceAdvanced,
    AlreadyInHandover,
    NotReady,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DivergenceReason {
    NotRepresentable,
    TargetUnavailable,
    TargetRejected,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Inspect(Inspection),
    AttemptUpgrade(Attempt),
    Report(ReportQuery),
    AskHandoverMarker(MarkerRequest),
    ReadyToHandover(ReadinessReport),
    HandoverCompleted(CompletionReport),
    Mirror(MirrorPayload),
    Divergence(DivergencePayload),
    RecoverFromFailure(RecoveryRequest),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    InspectionReported(InspectionReported),
    UpgradeCompleted(Completion),
    UpgradeRejected(Rejection),
    Reported(Reported),
    HandoverMarker(HandoverMarker),
    HandoverAccepted(HandoverAcceptance),
    HandoverFinalized(HandoverFinalization),
    MirrorAcknowledged(MirrorAcknowledgement),
    DivergenceAcknowledged(DivergenceAcknowledgement),
    RecoveryCompleted(RecoveryResult),
    HandoverRejected(HandoverRejection),
    RequestUnimplemented(RequestUnimplemented),
}

#[rustfmt::skip]
impl ContractVersion {
    pub fn new(payload: RawBytes) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RawBytes {
        &self.0
    }
    pub fn into_payload(self) -> RawBytes {
        self.0
    }
}
#[rustfmt::skip]
impl From<RawBytes> for ContractVersion {
    fn from(payload: RawBytes) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InspectionReported {
    pub fn new(payload: Vec<SupportedMigration>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<SupportedMigration> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<SupportedMigration> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<SupportedMigration>> for InspectionReported {
    fn from(payload: Vec<SupportedMigration>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RequestUnimplemented {
    pub fn new(payload: UnimplementedReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &UnimplementedReason {
        &self.0
    }
    pub fn into_payload(self) -> UnimplementedReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<UnimplementedReason> for RequestUnimplemented {
    fn from(payload: UnimplementedReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MarkerRequest {
    pub fn new(payload: ComponentName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentName {
        &self.0
    }
    pub fn into_payload(self) -> ComponentName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentName> for MarkerRequest {
    fn from(payload: ComponentName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HandoverAcceptance {
    pub fn new(payload: HandoverMarker) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &HandoverMarker {
        &self.0
    }
    pub fn into_payload(self) -> HandoverMarker {
        self.0
    }
}
#[rustfmt::skip]
impl From<HandoverMarker> for HandoverAcceptance {
    fn from(payload: HandoverMarker) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HandoverFinalization {
    pub fn new(payload: HandoverMarker) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &HandoverMarker {
        &self.0
    }
    pub fn into_payload(self) -> HandoverMarker {
        self.0
    }
}
#[rustfmt::skip]
impl From<HandoverMarker> for HandoverFinalization {
    fn from(payload: HandoverMarker) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Inspection {
    pub fn component(payload: ComponentName) -> Self {
        Self::Component(payload)
    }
}

#[rustfmt::skip]
impl ReportQuery {
    pub fn component(payload: ComponentName) -> Self {
        Self::Component(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn inspect(payload: Inspection) -> Self {
        Self::Inspect(payload)
    }
    pub fn attempt_upgrade(payload: Attempt) -> Self {
        Self::AttemptUpgrade(payload)
    }
    pub fn report(payload: ReportQuery) -> Self {
        Self::Report(payload)
    }
    pub fn ask_handover_marker(payload: ComponentName) -> Self {
        Self::AskHandoverMarker(MarkerRequest::new(payload))
    }
    pub fn ready_to_handover(payload: ReadinessReport) -> Self {
        Self::ReadyToHandover(payload)
    }
    pub fn handover_completed(payload: CompletionReport) -> Self {
        Self::HandoverCompleted(payload)
    }
    pub fn mirror(payload: MirrorPayload) -> Self {
        Self::Mirror(payload)
    }
    pub fn divergence(payload: DivergencePayload) -> Self {
        Self::Divergence(payload)
    }
    pub fn recover_from_failure(payload: RecoveryRequest) -> Self {
        Self::RecoverFromFailure(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn inspection_reported(payload: Vec<SupportedMigration>) -> Self {
        Self::InspectionReported(InspectionReported::new(payload))
    }
    pub fn upgrade_completed(payload: Completion) -> Self {
        Self::UpgradeCompleted(payload)
    }
    pub fn upgrade_rejected(payload: Rejection) -> Self {
        Self::UpgradeRejected(payload)
    }
    pub fn reported(payload: Reported) -> Self {
        Self::Reported(payload)
    }
    pub fn handover_marker(payload: HandoverMarker) -> Self {
        Self::HandoverMarker(payload)
    }
    pub fn handover_accepted(payload: HandoverMarker) -> Self {
        Self::HandoverAccepted(HandoverAcceptance::new(payload))
    }
    pub fn handover_finalized(payload: HandoverMarker) -> Self {
        Self::HandoverFinalized(HandoverFinalization::new(payload))
    }
    pub fn mirror_acknowledged(payload: MirrorAcknowledgement) -> Self {
        Self::MirrorAcknowledged(payload)
    }
    pub fn divergence_acknowledged(payload: DivergenceAcknowledgement) -> Self {
        Self::DivergenceAcknowledged(payload)
    }
    pub fn recovery_completed(payload: RecoveryResult) -> Self {
        Self::RecoveryCompleted(payload)
    }
    pub fn handover_rejected(payload: HandoverRejection) -> Self {
        Self::HandoverRejected(payload)
    }
    pub fn request_unimplemented(payload: UnimplementedReason) -> Self {
        Self::RequestUnimplemented(RequestUnimplemented::new(payload))
    }
}

#[rustfmt::skip]
impl From<Inspection> for Input {
    fn from(payload: Inspection) -> Self {
        Self::Inspect(payload)
    }
}

#[rustfmt::skip]
impl From<Attempt> for Input {
    fn from(payload: Attempt) -> Self {
        Self::AttemptUpgrade(payload)
    }
}

#[rustfmt::skip]
impl From<ReportQuery> for Input {
    fn from(payload: ReportQuery) -> Self {
        Self::Report(payload)
    }
}

#[rustfmt::skip]
impl From<MarkerRequest> for Input {
    fn from(payload: MarkerRequest) -> Self {
        Self::AskHandoverMarker(payload)
    }
}

#[rustfmt::skip]
impl From<ReadinessReport> for Input {
    fn from(payload: ReadinessReport) -> Self {
        Self::ReadyToHandover(payload)
    }
}

#[rustfmt::skip]
impl From<CompletionReport> for Input {
    fn from(payload: CompletionReport) -> Self {
        Self::HandoverCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<MirrorPayload> for Input {
    fn from(payload: MirrorPayload) -> Self {
        Self::Mirror(payload)
    }
}

#[rustfmt::skip]
impl From<DivergencePayload> for Input {
    fn from(payload: DivergencePayload) -> Self {
        Self::Divergence(payload)
    }
}

#[rustfmt::skip]
impl From<RecoveryRequest> for Input {
    fn from(payload: RecoveryRequest) -> Self {
        Self::RecoverFromFailure(payload)
    }
}

#[rustfmt::skip]
impl From<InspectionReported> for Output {
    fn from(payload: InspectionReported) -> Self {
        Self::InspectionReported(payload)
    }
}

#[rustfmt::skip]
impl From<Completion> for Output {
    fn from(payload: Completion) -> Self {
        Self::UpgradeCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<Rejection> for Output {
    fn from(payload: Rejection) -> Self {
        Self::UpgradeRejected(payload)
    }
}

#[rustfmt::skip]
impl From<Reported> for Output {
    fn from(payload: Reported) -> Self {
        Self::Reported(payload)
    }
}

#[rustfmt::skip]
impl From<HandoverMarker> for Output {
    fn from(payload: HandoverMarker) -> Self {
        Self::HandoverMarker(payload)
    }
}

#[rustfmt::skip]
impl From<HandoverAcceptance> for Output {
    fn from(payload: HandoverAcceptance) -> Self {
        Self::HandoverAccepted(payload)
    }
}

#[rustfmt::skip]
impl From<HandoverFinalization> for Output {
    fn from(payload: HandoverFinalization) -> Self {
        Self::HandoverFinalized(payload)
    }
}

#[rustfmt::skip]
impl From<MirrorAcknowledgement> for Output {
    fn from(payload: MirrorAcknowledgement) -> Self {
        Self::MirrorAcknowledged(payload)
    }
}

#[rustfmt::skip]
impl From<DivergenceAcknowledgement> for Output {
    fn from(payload: DivergenceAcknowledgement) -> Self {
        Self::DivergenceAcknowledged(payload)
    }
}

#[rustfmt::skip]
impl From<RecoveryResult> for Output {
    fn from(payload: RecoveryResult) -> Self {
        Self::RecoveryCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<HandoverRejection> for Output {
    fn from(payload: HandoverRejection) -> Self {
        Self::HandoverRejected(payload)
    }
}

#[rustfmt::skip]
impl From<RequestUnimplemented> for Output {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ContractVersion {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Version {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SupportedMigration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Inspection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Attempt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ReportQuery {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl InspectionReported {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Completion {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Rejection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Reported {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl UnimplementedReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RequestUnimplemented {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Date {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Time {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl HandoverMarker {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl MarkerRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ReadinessReport {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CompletionReport {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl MirrorPayload {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DivergencePayload {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RecoveryRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl HandoverAcceptance {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl HandoverFinalization {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl MirrorAcknowledgement {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DivergenceAcknowledgement {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RecoveryResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl HandoverRejection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl HandoverRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DivergenceReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_INSPECT: u64 = 0x0000000000000000;
    pub const INPUT_ATTEMPT_UPGRADE: u64 = 0x0001000000000000;
    pub const INPUT_REPORT: u64 = 0x0002000000000000;
    pub const INPUT_ASK_HANDOVER_MARKER: u64 = 0x0003000000000000;
    pub const INPUT_READY_TO_HANDOVER: u64 = 0x0004000000000000;
    pub const INPUT_HANDOVER_COMPLETED: u64 = 0x0005000000000000;
    pub const INPUT_MIRROR: u64 = 0x0006000000000000;
    pub const INPUT_DIVERGENCE: u64 = 0x0007000000000000;
    pub const INPUT_RECOVER_FROM_FAILURE: u64 = 0x0008000000000000;
    pub const OUTPUT_INSPECTION_REPORTED: u64 = 0x0100000000000000;
    pub const OUTPUT_UPGRADE_COMPLETED: u64 = 0x0101000000000000;
    pub const OUTPUT_UPGRADE_REJECTED: u64 = 0x0102000000000000;
    pub const OUTPUT_REPORTED: u64 = 0x0103000000000000;
    pub const OUTPUT_HANDOVER_MARKER: u64 = 0x0104000000000000;
    pub const OUTPUT_HANDOVER_ACCEPTED: u64 = 0x0105000000000000;
    pub const OUTPUT_HANDOVER_FINALIZED: u64 = 0x0106000000000000;
    pub const OUTPUT_MIRROR_ACKNOWLEDGED: u64 = 0x0107000000000000;
    pub const OUTPUT_DIVERGENCE_ACKNOWLEDGED: u64 = 0x0108000000000000;
    pub const OUTPUT_RECOVERY_COMPLETED: u64 = 0x0109000000000000;
    pub const OUTPUT_HANDOVER_REJECTED: u64 = 0x010A000000000000;
    pub const OUTPUT_REQUEST_UNIMPLEMENTED: u64 = 0x010B000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Inspect,
    AttemptUpgrade,
    Report,
    AskHandoverMarker,
    ReadyToHandover,
    HandoverCompleted,
    Mirror,
    Divergence,
    RecoverFromFailure,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    InspectionReported,
    UpgradeCompleted,
    UpgradeRejected,
    Reported,
    HandoverMarker,
    HandoverAccepted,
    HandoverFinalized,
    MirrorAcknowledged,
    DivergenceAcknowledged,
    RecoveryCompleted,
    HandoverRejected,
    RequestUnimplemented,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Inspect(_) => InputRoute::Inspect,
            Self::AttemptUpgrade(_) => InputRoute::AttemptUpgrade,
            Self::Report(_) => InputRoute::Report,
            Self::AskHandoverMarker(_) => InputRoute::AskHandoverMarker,
            Self::ReadyToHandover(_) => InputRoute::ReadyToHandover,
            Self::HandoverCompleted(_) => InputRoute::HandoverCompleted,
            Self::Mirror(_) => InputRoute::Mirror,
            Self::Divergence(_) => InputRoute::Divergence,
            Self::RecoverFromFailure(_) => InputRoute::RecoverFromFailure,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Inspect(_) => short_header::INPUT_INSPECT,
            Self::AttemptUpgrade(_) => short_header::INPUT_ATTEMPT_UPGRADE,
            Self::Report(_) => short_header::INPUT_REPORT,
            Self::AskHandoverMarker(_) => short_header::INPUT_ASK_HANDOVER_MARKER,
            Self::ReadyToHandover(_) => short_header::INPUT_READY_TO_HANDOVER,
            Self::HandoverCompleted(_) => short_header::INPUT_HANDOVER_COMPLETED,
            Self::Mirror(_) => short_header::INPUT_MIRROR,
            Self::Divergence(_) => short_header::INPUT_DIVERGENCE,
            Self::RecoverFromFailure(_) => short_header::INPUT_RECOVER_FROM_FAILURE,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_INSPECT => Ok(InputRoute::Inspect),
            short_header::INPUT_ATTEMPT_UPGRADE => Ok(InputRoute::AttemptUpgrade),
            short_header::INPUT_REPORT => Ok(InputRoute::Report),
            short_header::INPUT_ASK_HANDOVER_MARKER => Ok(InputRoute::AskHandoverMarker),
            short_header::INPUT_READY_TO_HANDOVER => Ok(InputRoute::ReadyToHandover),
            short_header::INPUT_HANDOVER_COMPLETED => Ok(InputRoute::HandoverCompleted),
            short_header::INPUT_MIRROR => Ok(InputRoute::Mirror),
            short_header::INPUT_DIVERGENCE => Ok(InputRoute::Divergence),
            short_header::INPUT_RECOVER_FROM_FAILURE => {
                Ok(InputRoute::RecoverFromFailure)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::InspectionReported(_) => OutputRoute::InspectionReported,
            Self::UpgradeCompleted(_) => OutputRoute::UpgradeCompleted,
            Self::UpgradeRejected(_) => OutputRoute::UpgradeRejected,
            Self::Reported(_) => OutputRoute::Reported,
            Self::HandoverMarker(_) => OutputRoute::HandoverMarker,
            Self::HandoverAccepted(_) => OutputRoute::HandoverAccepted,
            Self::HandoverFinalized(_) => OutputRoute::HandoverFinalized,
            Self::MirrorAcknowledged(_) => OutputRoute::MirrorAcknowledged,
            Self::DivergenceAcknowledged(_) => OutputRoute::DivergenceAcknowledged,
            Self::RecoveryCompleted(_) => OutputRoute::RecoveryCompleted,
            Self::HandoverRejected(_) => OutputRoute::HandoverRejected,
            Self::RequestUnimplemented(_) => OutputRoute::RequestUnimplemented,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::InspectionReported(_) => short_header::OUTPUT_INSPECTION_REPORTED,
            Self::UpgradeCompleted(_) => short_header::OUTPUT_UPGRADE_COMPLETED,
            Self::UpgradeRejected(_) => short_header::OUTPUT_UPGRADE_REJECTED,
            Self::Reported(_) => short_header::OUTPUT_REPORTED,
            Self::HandoverMarker(_) => short_header::OUTPUT_HANDOVER_MARKER,
            Self::HandoverAccepted(_) => short_header::OUTPUT_HANDOVER_ACCEPTED,
            Self::HandoverFinalized(_) => short_header::OUTPUT_HANDOVER_FINALIZED,
            Self::MirrorAcknowledged(_) => short_header::OUTPUT_MIRROR_ACKNOWLEDGED,
            Self::DivergenceAcknowledged(_) => {
                short_header::OUTPUT_DIVERGENCE_ACKNOWLEDGED
            }
            Self::RecoveryCompleted(_) => short_header::OUTPUT_RECOVERY_COMPLETED,
            Self::HandoverRejected(_) => short_header::OUTPUT_HANDOVER_REJECTED,
            Self::RequestUnimplemented(_) => short_header::OUTPUT_REQUEST_UNIMPLEMENTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_INSPECTION_REPORTED => {
                Ok(OutputRoute::InspectionReported)
            }
            short_header::OUTPUT_UPGRADE_COMPLETED => Ok(OutputRoute::UpgradeCompleted),
            short_header::OUTPUT_UPGRADE_REJECTED => Ok(OutputRoute::UpgradeRejected),
            short_header::OUTPUT_REPORTED => Ok(OutputRoute::Reported),
            short_header::OUTPUT_HANDOVER_MARKER => Ok(OutputRoute::HandoverMarker),
            short_header::OUTPUT_HANDOVER_ACCEPTED => Ok(OutputRoute::HandoverAccepted),
            short_header::OUTPUT_HANDOVER_FINALIZED => Ok(OutputRoute::HandoverFinalized),
            short_header::OUTPUT_MIRROR_ACKNOWLEDGED => {
                Ok(OutputRoute::MirrorAcknowledged)
            }
            short_header::OUTPUT_DIVERGENCE_ACKNOWLEDGED => {
                Ok(OutputRoute::DivergenceAcknowledged)
            }
            short_header::OUTPUT_RECOVERY_COMPLETED => Ok(OutputRoute::RecoveryCompleted),
            short_header::OUTPUT_HANDOVER_REJECTED => Ok(OutputRoute::HandoverRejected),
            short_header::OUTPUT_REQUEST_UNIMPLEMENTED => {
                Ok(OutputRoute::RequestUnimplemented)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}
